# Default values for node-b.

sabnzbd: { version: "4.5.5" }
nzbtomedia: { version: "12.1.13" }
oauth2proxy: { version: "v7.12.0" }
nzbhydra2: { version: "7.19.2" }
filebrowser: { version: "v2.45.0" }
sonarr: { version: "4.0.15" }
radarr: { version: "5.28.0" }
bazarr: { version: "1.5.3" }
readarr: { version: "0.4.18-develop" }
prowlarr: { version: "2.1.5" }

# storage class name for local volumes
storage_class_name: persistent
storage_class_name_downloads: persistent-2
# library nfs storage configuration
library:
    nfs_server: 192.168.30.17

ingress:
    host: usenet.hutter.cloud

readarr_replicas: 0
