# Default values for node-b.

calibre: { version: "9.1.0" }
calibreweb: { version: "0.6.25" }
oauth2proxy: { version: "v7.14.2" }



# storage class name for local volumes
storage_class_name: persistent

# library nfs storage configuration
library:
  nfs_server: 192.168.30.17

ingress:
  calibre: calibre-content.hutter.cloud
  web: calibre.hutter.cloud
  opds: calibre-opds.hutter.cloud
