apiVersion: v2
name: jenkins
description: install and configure jenkins
type: application
version: "5.8.140"

dependencies:
- name: jenkins
  version: "5.8.140"
  repository: "https://charts.jenkins.io"
